# Generated by Django 2.2.5 on 2020-09-12 05:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcommerce_shipping', '0005_auto_20200912_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatRateShipment',
            fields=[
                ('shipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcommerce_shipping.Shipment')),
                ('shipping_rate', models.CharField(blank=True, help_text='Shipping rate at the moment the shipment was generated', max_length=100, verbose_name='shipping rate')),
            ],
            options={
                'verbose_name': 'flat rate shipment',
                'verbose_name_plural': 'flat rate shipments',
            },
            bases=('wagtailcommerce_shipping.shipment',),
        ),
        migrations.CreateModel(
            name='FlatRateShippingMethod',
            fields=[
                ('shippingmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcommerce_shipping.ShippingMethod')),
                ('generate_shipping_label', models.BooleanField(verbose_name='generate shipping label')),
                ('label_heading', wagtail.core.fields.RichTextField(verbose_name='label heading')),
                ('shipping_rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='shipping rate')),
                ('label_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wagtailcommerce_images', to='wagtailimages.Image', verbose_name='label logo')),
            ],
            options={
                'verbose_name': 'flat rate shipping method',
                'verbose_name_plural': 'flat rate shipping methods',
            },
            bases=('wagtailcommerce_shipping.shippingmethod', models.Model),
        ),
    ]
