# Generated by Django 2.2.5 on 2020-10-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_flat_rate_shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatrateshippingmethod',
            name='label_display_product_list',
            field=models.BooleanField(default=True, verbose_name='display product list on label'),
        ),
    ]
