# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 21:12
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_orders', '0022_auto_20180410_1812'),
        ('wagtailcommerce_shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='wagtailcommerce_orders.Order'),
            preserve_default=False,
        ),
    ]
