# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import wagtailcommerce.shipping.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcommerce_shipping', '0002_shipment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='content_type',
            field=models.ForeignKey(default=92, on_delete=models.SET(wagtailcommerce.shipping.models.get_default_shipment_content_type), related_name='shipments', to='contenttypes.ContentType', verbose_name='content type'),
            preserve_default=False,
        ),
    ]
