# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcommerce_products', '0012_auto_20171208_1618'),
        ('wagtailcommerce_stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('locked', 'Locked'), ('canceled', 'Canceled')], default='open', max_length=128, verbose_name='status')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='token')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='wagtailcommerce_stores.Store')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'carts',
            },
        ),
        migrations.CreateModel(
            name='CartLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wagtailcommerce_carts.Cart')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcommerce_products.ProductVariant', verbose_name='product')),
            ],
            options={
                'verbose_name': 'cart line',
                'verbose_name_plural': 'cart lines',
            },
        ),
    ]
