# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('replaced', 'Replaced'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='open', max_length=128, verbose_name='status'),
        ),
    ]
