# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_promotions', '0004_auto_20180129_2246'),
        ('wagtailcommerce_carts', '0003_auto_20180129_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcommerce_promotions.Coupon'),
        ),
    ]
