# Generated by Django 2.2.5 on 2019-09-10 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_carts', '0005_auto_20180221_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='wagtailcommerce_stores.Store'),
        ),
        migrations.AlterField(
            model_name='cartline',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcommerce_products.ProductVariant', verbose_name='product'),
        ),
    ]
