# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcommerce_promotions', '0001_initial'),
        ('wagtailcommerce_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcommerce_promotions.Voucher', verbose_name='voucher'),
        ),
    ]
