# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_orders', '0004_auto_20180122_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='identifier',
            field=models.CharField(db_index=True, default='', max_length=8, unique=True, verbose_name='identifier'),
            preserve_default=False,
        ),
    ]
