# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_orders', '0006_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='wagtailcommerce_promotions.Voucher', verbose_name='voucher'),
        ),
    ]
