# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_orders', '0007_auto_20180123_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_paid',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
