# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_orders', '0010_auto_20180126_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='product_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='product thumbnail'),
        ),
    ]
