# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_orders', '0011_orderline_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='order',
            name='voucher_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='voucher_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='voucher_mode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='voucher_type',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='voucher_amount',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='voucher_mode',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='voucher_type',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='voucher_voucher_code',
        ),
    ]
