# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_promotions', '0002_auto_20180129_2204'),
        ('wagtailcommerce_orders', '0012_auto_20180129_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='wagtailcommerce_promotions.Coupon', verbose_name='coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='coupon amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='coupon code'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_mode',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage')], max_length=20, verbose_name='coupon mode'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_type',
            field=models.CharField(blank=True, choices=[('order_total', 'Discount on order total')], max_length=20, verbose_name='coupon type'),
        ),
    ]
