# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-21 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_orders', '0015_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment pending'), ('awaiting_payment_confirmation', 'Awaiting payment confirmation'), ('awaiting_payment_authorization', 'Awaiting payment authorization'), ('paid', 'Paid'), ('cancellled', 'Cancelled')], default='payment_pending', max_length=30, verbose_name='status'),
        ),
    ]
