# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_orders', '0018_orderline_product_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date_placed',), 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
    ]
