# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 13:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_orders', '0019_auto_20180307_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wagtailcommerce_orders.Order'),
        ),
    ]
