# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_orders', '0020_auto_20180307_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='value stored in millimeters', max_digits=12, null=True, verbose_name='depth'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='value stored in millimeters', max_digits=12, null=True, verbose_name='height'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='value stored in grams', max_digits=12, null=True, verbose_name='weight'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='value stored in millimeters', max_digits=12, null=True, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon_mode',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed amount'), ('percentage', 'Percentage')], max_length=20, verbose_name='coupon mode'),
        ),
    ]
