# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_orders', '0021_auto_20180410_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment pending'), ('awaiting_payment_confirmation', 'Awaiting payment confirmation'), ('awaiting_payment_authorization', 'Awaiting payment authorization'), ('paid', 'Paid'), ('shipment_generated', 'Shipment generated'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancellled', 'Cancelled')], default='payment_pending', max_length=30, verbose_name='status'),
        ),
    ]
