# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_orders', '0022_auto_20180410_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_paid',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='date paid'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_placed',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date placed'),
        ),
    ]
