# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-03 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import wagtailcommerce.payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Internal name to uniquely identify this payment method', max_length=255, verbose_name='Identifier')),
                ('display_name', models.CharField(blank=True, help_text='How the payment method will be displayed on the frontend. If empty, identifier will be used instead', max_length=255, verbose_name='Display name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified on')),
                ('content_type', models.ForeignKey(on_delete=models.SET(wagtailcommerce.payments.models.get_default_payment_method_content_type), related_name='payment_methods', to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'verbose_name': 'Payment method',
                'verbose_name_plural': 'Payment methods',
                'abstract': False,
            },
        ),
    ]
