# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtailcommerce.products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcommerce_stores', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('active', models.BooleanField(verbose_name='active')),
                ('available_on', models.DateTimeField(blank=True, null=True, verbose_name='available on')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('content_type', models.ForeignKey(on_delete=models.SET(wagtailcommerce.products.models.get_default_product_content_type), related_name='products', to='contenttypes.ContentType', verbose_name='content type')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='wagtailcommerce_stores.Store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=32, unique=True, verbose_name='SKU')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='price')),
                ('content_type', models.ForeignKey(on_delete=models.SET(wagtailcommerce.products.models.get_default_product_variant_content_type), related_name='product_variants', to='contenttypes.ContentType', verbose_name='content type')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='wagtailcommerce_products.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
