# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_products', '0002_auto_20170917_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', help_text='The name of the product as it will appear in URLs e.g http://domain.com/store/[product-slug]/', max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
