# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_products', '0005_auto_20170918_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
