# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcommerce_products', '0007_auto_20171125_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='imageset',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
