# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcommerce_products', '0009_auto_20171126_1416'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imageset',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
