# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_products', '0010_auto_20171126_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageset',
            name='name',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='stock'),
        ),
    ]
