# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_products', '0011_auto_20171128_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wagtailcommerce_images', to='wagtailimages.Image', verbose_name='image'),
        ),
    ]
