# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_products', '0012_auto_20171208_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified on'),
        ),
    ]
