# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_products', '0014_product_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='identifier',
            field=models.CharField(db_index=True, max_length=8, unique=True, verbose_name='identifier'),
        ),
    ]
