# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-21 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_products', '0016_auto_20180129_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='value stored in millimeters', max_digits=12, null=True, verbose_name='depth'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='value stored in millimeters', max_digits=12, null=True, verbose_name='height'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='value stored in grams', max_digits=12, null=True, verbose_name='weight'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='value stored in millimeters', max_digits=12, null=True, verbose_name='width'),
        ),
    ]
