# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-24 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_products', '0018_auto_20180223_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified on'),
        ),
    ]
