# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-11 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_products', '0021_product_preview_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='presale',
            field=models.BooleanField(default=False, verbose_name='presale'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchasing_enabled',
            field=models.BooleanField(default=True, verbose_name='purchasing enabled'),
        ),
    ]
