# Generated by Django 2.2.5 on 2020-09-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_products', '0025_auto_20200912_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='regular_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='single_price',
        ),
        migrations.AddField(
            model_name='product',
            name='percentage_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter a value from 0 to 100 in order to offer a percentage discount on this product.', max_digits=12, null=True, verbose_name='percentage discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manually set a fixed sale price. It will be the end amount charged to customers before promotions are applied.', max_digits=12, null=True, verbose_name='sale price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='regular price'),
        ),
    ]
