# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcommerce_products', '0005_auto_20170918_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomShoe',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcommerce_products.Product')),
            ],
            options={
                'verbose_name': 'shoe',
                'verbose_name_plural': 'shoes',
            },
            bases=('wagtailcommerce_products.product',),
        ),
        migrations.CreateModel(
            name='CustomShoeVariant',
            fields=[
                ('productvariant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcommerce_products.ProductVariant')),
            ],
            options={
                'verbose_name': 'shoe variant',
                'verbose_name_plural': 'shoe variants',
            },
            bases=('wagtailcommerce_products.productvariant',),
        ),
        migrations.CreateModel(
            name='ShoeColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
            options={
                'verbose_name': 'shoe color',
                'verbose_name_plural': 'shoe colors',
            },
        ),
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_size', models.CharField(max_length=10, verbose_name='us size')),
            ],
            options={
                'verbose_name': 'shoe size',
                'verbose_name_plural': 'shoe sizes',
            },
        ),
        migrations.CreateModel(
            name='ShoeVariantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image')),
                ('variant', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wagtailcommerce_tests_demoproducts.CustomShoeVariant')),
            ],
            options={
                'verbose_name': 'shoe variant image',
                'verbose_name_plural': 'shoe variant images',
            },
        ),
        migrations.AddField(
            model_name='customshoevariant',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoe_variants', to='wagtailcommerce_tests_demoproducts.ShoeColor'),
        ),
        migrations.AddField(
            model_name='customshoevariant',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='customshoevariant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoe_variants', to='wagtailcommerce_tests_demoproducts.ShoeSize'),
        ),
    ]
