# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcommerce_products', '0005_auto_20170918_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='code')),
                ('voucher_type', models.CharField(choices=[('category', 'Products in categories'), ('products', 'Specific products'), ('shipping', 'Shipping cost')], max_length=20, verbose_name='voucher type')),
                ('voucher_mode', models.CharField(choices=[('fixed', 'Fixed amount'), ('percentage', 'Percentage')], max_length=20, verbose_name='voucher mode')),
                ('voucher_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='voucher amount')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='usage limit')),
                ('used', models.PositiveIntegerField(default=0, editable=False)),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='valid from')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='valid from')),
                ('auto_generated', models.BooleanField(editable=False, verbose_name='auto generated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('product_variants', models.ManyToManyField(related_name='vouchers', to='wagtailcommerce_products.ProductVariant')),
            ],
            options={
                'verbose_name': 'voucher',
                'verbose_name_plural': 'vouchers',
            },
        ),
    ]
