# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_products', '0016_auto_20180129_2204'),
        ('wagtailcommerce_orders', '0012_auto_20180129_2204'),
        ('wagtailcommerce_promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='code')),
                ('coupon_type', models.CharField(choices=[('order_total', 'Discount on order total')], max_length=20, verbose_name='coupon type')),
                ('coupon_mode', models.CharField(choices=[('percentage', 'Percentage')], max_length=20, verbose_name='coupon mode')),
                ('coupon_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='coupon amount')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='usage limit')),
                ('used', models.PositiveIntegerField(default=0, editable=False)),
                ('auto_assign_to_new_users', models.BooleanField(verbose_name='auto assign to new users')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='valid from')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='valid from')),
                ('auto_generated', models.BooleanField(editable=False, verbose_name='auto generated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('product_variants', models.ManyToManyField(blank=True, related_name='coupons', to='wagtailcommerce_products.ProductVariant')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
            },
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='product_variants',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
