# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_promotions', '0002_auto_20180129_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='auto_generated',
            field=models.BooleanField(default=False, editable=False, verbose_name='auto generated'),
        ),
    ]
