# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_promotions', '0006_auto_20180317_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='added_to_cart',
            new_name='times_added_to_cart',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='used',
            new_name='times_used',
        ),
    ]
