# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_promotions', '0007_auto_20180319_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='times_added_to_cart',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='times added to cart'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='times_used',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='times used'),
        ),
    ]
