# Generated by Django 2.2.5 on 2019-09-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_promotions', '0009_coupon_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Only apply to products in selected categories', limit_choices_to={'numchild': 0}, related_name='coupons', to='wagtailcommerce_products.Category'),
        ),
    ]
