# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 16:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('default_shipping_address', models.BooleanField(default=False, verbose_name='Default shipping address')),
                ('default_billing_address', models.BooleanField(default=False, verbose_name='Default billing address')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last name')),
                ('street_address_1', models.CharField(blank=True, max_length=255, verbose_name='Address (line 1)')),
                ('street_address_2', models.CharField(blank=True, max_length=255, verbose_name='Address (line 2)')),
                ('street_number', models.CharField(blank=True, max_length=255, verbose_name='Street number')),
                ('floor', models.CharField(blank=True, max_length=255, verbose_name='Floor')),
                ('apartment_number', models.CharField(blank=True, max_length=255, verbose_name='Apartment number')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City / Town')),
                ('district', models.CharField(blank=True, max_length=255, verbose_name='District / Neighborhood')),
                ('country_area', models.CharField(blank=True, max_length=255, verbose_name='State / Province / Region')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, max_length=64, verbose_name='Postal code')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone number')),
                ('security_access_code', models.CharField(blank=True, max_length=150, verbose_name='Security access code')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ('-created',),
            },
        ),
    ]
