# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-21 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-default_shipping_address', '-default_billing_address', '-created'), 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
