# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 20:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0039_collectionviewrestriction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('code', models.CharField(help_text='ISO 4217 3 letter code', max_length=3, verbose_name='code')),
                ('symbol', models.CharField(help_text='As displayed on frontend', max_length=30, verbose_name='symbol')),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'verbose_name': 'currency',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='tax rate (percentage)')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='wagtailcommerce_stores.Currency')),
                ('site', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to='wagtailcore.Site')),
            ],
            options={
                'verbose_name_plural': 'stores',
                'verbose_name': 'store',
            },
        ),
    ]
