# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='checkout_enabled',
            field=models.BooleanField(default=True, verbose_name='checkout enabled'),
        ),
    ]
