# Generated by Django 2.2.5 on 2019-09-10 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcommerce_stores', '0002_store_checkout_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='wagtailcommerce_stores.Currency'),
        ),
    ]
